#! /bin/bash

cp .gitconfig .gitignore_global .git-completion.bash .vimrc ~
cp Xcode/CodeSnippets/* ~/Library/Developer/Xcode/UserData/CodeSnippets/
cp Xcode/FontAndColorThemes/* ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
git config --global core.excludesfile ~/.gitignore_global
